# Learn more about configuring your app:
# https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "129648e8356f007bc7b7f0199333dcdb"
name = "NearbyPulse"
application_url = "https://app.nearbypulse.app"
embedded = true

[access_scopes]
scopes = ""

[webhooks]
api_version = "2026-07"


[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = ["app/scopes_update"]

[[webhooks.subscriptions]]
uri = "/webhooks/compliance"
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]

[auth]
redirect_urls = [
  "https://app.nearbypulse.app/auth/callback"
]

[build]
automatically_update_urls_on_dev = false

[app_proxy]
url = "https://app.nearbypulse.app/api/nearby-activity"
subpath = "nearby-pulse"
prefix = "apps"

[[extensions]]
name = "nearby-pulse-extension"
handle = "social-proof"
type = "theme"
path = "extensions/nearby-pulse-extension"
